repos:
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--check-untyped-defs]

  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: v2.6.2
    hooks:
      - id: pip-compile-multi-verify

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-added-large-files
        exclude: \.(geojson)$
      - id: check-yaml
        exclude: ^helm/superset/templates/
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--ignore-path=./frontend/.prettierignore"]
        files: "frontend"
