version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  expenses:
    image: dmitriyvasil1986/expenses:latest
    env_file: ./.env
    volumes:
      - ./expense_counter:/app/expense_counter
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./expense_counter/static:/static
      - ./images:/images
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - expenses
      - db
