version: "3.7"

volumes:
  main_js:
    external: false

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: expenses
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      SECRET: ${SECRET}
      DEBUG: ${DEBUG}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./backend:/app
      - main_js:/app/static/js/
    depends_on:
      - db

  frontend:
    image: node:16
    volumes:
      - main_js:/frontend/dist/
      - ./frontend:/frontend
    command: ["/bin/sh", "/frontend/run_script.sh", "build"]
    depends_on:
      - backend
      - db
