# Generated by Django 4.1.1 on 2024-02-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_shop_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="count",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
