# Generated by Django 4.1.1 on 2022-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_price_date_remove_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
