# Generated by Django 4.1.1 on 2024-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_transaction_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopaddress",
            name="local_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
