# Generated by Django 4.1.1 on 2024-02-28 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_shop_sub_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="sub_category",
            new_name="category",
        ),
    ]
