# Generated by Django 4.2.17 on 2024-12-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="main.category",
            ),
        ),
    ]
