# Generated by Django 4.1.1 on 2024-02-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_transaction_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="main.subcategory",
            ),
        ),
    ]
