# Generated by Django 4.1.1 on 2024-02-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_shop_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="shop",
        ),
        migrations.AddField(
            model_name="transaction",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transanctions",
                to="main.shopaddress",
            ),
            preserve_default=False,
        ),
    ]
