# Generated by Django 4.1.1 on 2024-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_shop_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="icon",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
