# Generated by Django 4.1.1 on 2024-02-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_shop_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shops",
                to="main.category",
            ),
        ),
    ]
